name: getnet_pos
description: Plugin for getnet POS
version: 1.0.0

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: io.zafeapps.getnet_pos
    pluginClass: GetnetPosPlugin
